_target_: pytorch_lightning.Trainer

gpus: 4
accelerator: ddp
benchmark: true
resume_from_checkpoint: ${resume}
plugins:
  _target_: pytorch_lightning.plugins.DDPPlugin
  find_unused_parameters: False
