_target_: pytorch_lightning.Trainer

gpus: 8
accelerator: gpu
strategy: 
  _target_: pytorch_lightning.strategies.DDPStrategy
  find_unused_parameters: False
benchmark: true
resume_from_checkpoint: ${resume}