# output paths for hydra logs
run:
  dir: results/${name}
sweep:
  dir: results/multiruns/${name}
  subdir: ${hydra.job.num}

# you can set here environment variables that are universal for all users
# for system specific variables (like data paths) it's better to use .env file!
job:
  env_set:
    EXAMPLE_VAR: "example_value"
