_target_: src.tasks.text.MaskedLanguageModelTask
model:
  _target_: transformers.BertForPreTraining
  config:
    _target_: transformers.BertConfig
optimizer:
  _target_: src.optim.OptimRegime
  regime:
    - epoch: 0
      optimizer: SGD
      lr: 0.1
      momentum: 0.9
    - epoch: 81
      lr: 0.01
    - epoch: 122
      lr: 0.001
