_target_: src.tasks.text.ImageFromTextTask
model:
  _target_: torchvision.models.resnet50
  pretrained: false
  num_classes: 768
text_model:
  _target_: transformers.AutoModel.from_pretrained
  pretrained_model_name_or_path: sentence-transformers/all-mpnet-base-v2
