_target_: src.tasks.text.ImageToTextTask
model:
  _target_: src.models.huggingface.ImageToTextModel
  image_model:
    _target_: torchvision.models.resnet50
    pretrained: false
  text_model:
    _target_: transformers.T5ForConditionalGeneration.from_pretrained
    pretrained_model_name_or_path: "t5-small"
  freeze_image_model: false
  freeze_text_model: true
  remove_pooler: false
