_target_: src.tasks.text.ImageToTextTask
model:
  _target_: src.models.huggingface.ImageToTextModel
  image_model:
    _target_: src.models.resnet.resnet
    dataset: imagenet
    num_classes: 512
    depth: 50
  text_model:
    _target_: transformers.T5ForConditionalGeneration.from_pretrained
    pretrained_model_name_or_path: "t5-small"
  freeze_image_model: false
  freeze_text_model: true
optimizer:
  _target_: src.optim.OptimConfig.instantiate
  optimizer:
    _target_: src.optim.lars.LARS
    lr: 1.0
    momentum: 0.9
    weight_decay: 0.0002
    nesterov: false
    trust_coefficient: 0.001
    eps: 1e-8
  optimizer_filters:
    - filter:
        _target_: src.optim.filter.OnlyBiasBN
        exclude: true
    - filter:
        _target_: src.optim.filter.OnlyBiasBN
      skip_scale: true          
  lr_scheduler:
    _target_: src.optim.scheduler.PolynomialWarmUpDecay
    lr: ${task.optimizer.optimizer.lr}
    warmup_steps: 5000
    total_steps: 50000
    init_lr: 0.
    final_lr: 0.0001
    decay_power: 2.0
  interval: step